import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("search", "routes/search.tsx"),
  route("laptops", "routes/category-laptops.tsx"),
  route("smartphones", "routes/category-smartphones.tsx"),
  route("televisions", "routes/category-televisions.tsx"),
  route("refrigerators", "routes/category-refrigerators.tsx"),
  route("washing-machines", "routes/category-washing-machines.tsx"),
  route("tws", "routes/category-tws.tsx"),
  route("headphones", "routes/category-headphones.tsx"),
  route("cameras", "routes/category-cameras.tsx"),
  route("mobile-phones", "routes/category-mobile-phones.tsx"),
  route("products/:productId/:productSlug?", "routes/product-detail.tsx"),
  route("compare", "routes/compare.tsx"),
  route("wishlist", "routes/wishlist.tsx"),
  route("deals", "routes/deals.tsx"),
  route("tracker", "routes/tracker.tsx"),
  route("platforms", "routes/platforms.tsx"),
  route("how-it-works", "routes/how-it-works.tsx"),
  route("about", "routes/about.tsx"),
  route("contact", "routes/contact.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("disclaimer", "routes/disclaimer.tsx"),
  route("assistant", "routes/assistant.tsx"),
  route("sign-in", "routes/sign-in.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("check-email", "routes/check-email.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("account", "routes/account.tsx"),
  route("admin/*", "routes/admin.tsx"),
  route("robots.txt", "routes/robots[.]txt.ts"),
  route("sitemap.xml", "routes/sitemap[.]xml.ts"),
  route("sitemaps/static.xml", "routes/sitemaps.static[.]xml.ts"),
  route("sitemaps/categories.xml", "routes/sitemaps.categories[.]xml.ts"),
  route("sitemaps/products/:page.xml", "routes/sitemaps.products.$page[.]xml.ts"),
  route("health", "routes/frontend-health.ts"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
