"""Additional curated matching cases for Matching V2.

These pairs extend GOLDEN_PAIRS. Labels are curated-benchmark only.
False exact merge remains worse than unmatched.
"""

from __future__ import annotations

from typing import Any


def _p(
    pid: str,
    category: str,
    left_title: str,
    left_specs: dict[str, Any],
    right_title: str,
    right_specs: dict[str, Any],
    expected: str,
) -> dict[str, Any]:
    return {
        "id": pid,
        "category": category,
        "left": {"title": left_title, "specs": left_specs},
        "right": {"title": right_title, "specs": right_specs},
        "expected": expected,
    }


EXTRA_GOLDEN_PAIRS: list[dict[str, Any]] = [
    # --- Smartphones: storage / RAM / generation / brand ---
    _p(
        "phone_iphone15_128_vs_256",
        "smartphone",
        "Apple iPhone 15 128GB Blue",
        {"brand": "apple", "family": "iphone_15", "storage_gb": 128, "model_codes": ["MTP03HN/A"]},
        "Apple iPhone 15 256GB Blue",
        {"brand": "apple", "family": "iphone_15", "storage_gb": 256, "model_codes": ["MTP43HN/A"]},
        "variant",
    ),
    _p(
        "phone_iphone15_ram_mismatch",
        "smartphone",
        "Apple iPhone 15 6GB 128GB",
        {"brand": "apple", "family": "iphone_15", "ram_gb": 6, "storage_gb": 128, "model_codes": ["MTP03HN/A"]},
        "Apple iPhone 15 8GB 128GB",
        {"brand": "apple", "family": "iphone_15", "ram_gb": 8, "storage_gb": 128, "model_codes": ["MTP03HN/A"]},
        "variant",
    ),
    _p(
        "phone_iphone15_vs_15_pro",
        "smartphone",
        "Apple iPhone 15 128GB",
        {"brand": "apple", "family": "iphone_15", "storage_gb": 128, "model_codes": ["MTP03HN/A"]},
        "Apple iPhone 15 Pro 128GB",
        {"brand": "apple", "family": "iphone_15_pro", "storage_gb": 128, "model_codes": ["MTUX3HN/A"]},
        "related",
    ),
    _p(
        "phone_iphone15_vs_15_plus",
        "smartphone",
        "Apple iPhone 15 128GB",
        {"brand": "apple", "family": "iphone_15", "storage_gb": 128, "model_codes": ["MTP03HN/A"]},
        "Apple iPhone 15 Plus 128GB",
        {"brand": "apple", "family": "iphone_15_plus", "storage_gb": 128, "model_codes": ["MU0F3HN/A"]},
        "related",
    ),
    _p(
        "phone_iphone15_vs_16",
        "smartphone",
        "Apple iPhone 15 128GB",
        {"brand": "apple", "family": "iphone_15", "storage_gb": 128, "model_codes": ["MTP03HN/A"]},
        "Apple iPhone 16 128GB",
        {"brand": "apple", "family": "iphone_16", "storage_gb": 128, "model_codes": ["MYEV3HN/A"]},
        "related",
    ),
    _p(
        "phone_s24_vs_s24_ultra",
        "smartphone",
        "Samsung Galaxy S24 8GB 256GB",
        {"brand": "samsung", "family": "galaxy_s24", "ram_gb": 8, "storage_gb": 256, "model_codes": ["SM-S921B"]},
        "Samsung Galaxy S24 Ultra 12GB 256GB",
        {"brand": "samsung", "family": "galaxy_s24_ultra", "ram_gb": 12, "storage_gb": 256, "model_codes": ["SM-S928B"]},
        "related",
    ),
    _p(
        "phone_s24_vs_s23",
        "smartphone",
        "Samsung Galaxy S24 8GB 128GB",
        {"brand": "samsung", "family": "galaxy_s24", "ram_gb": 8, "storage_gb": 128, "model_codes": ["SM-S921B"]},
        "Samsung Galaxy S23 8GB 128GB",
        {"brand": "samsung", "family": "galaxy_s23", "ram_gb": 8, "storage_gb": 128, "model_codes": ["SM-S911B"]},
        "related",
    ),
    _p(
        "phone_s24_ram_8_vs_12",
        "smartphone",
        "Samsung Galaxy S24 8GB 256GB",
        {"brand": "samsung", "family": "galaxy_s24", "ram_gb": 8, "storage_gb": 256, "model_codes": ["SM-S921B"]},
        "Samsung Galaxy S24 12GB 256GB",
        {"brand": "samsung", "family": "galaxy_s24", "ram_gb": 12, "storage_gb": 256, "model_codes": ["SM-S921B"]},
        "variant",
    ),
    _p(
        "phone_pixel8_vs_pixel8_pro",
        "smartphone",
        "Google Pixel 8 8GB 128GB",
        {"brand": "google", "family": "pixel_8", "ram_gb": 8, "storage_gb": 128, "model_codes": ["G9BQD"]},
        "Google Pixel 8 Pro 12GB 128GB",
        {"brand": "google", "family": "pixel_8_pro", "ram_gb": 12, "storage_gb": 128, "model_codes": ["GC3VE"]},
        "related",
    ),
    _p(
        "phone_oneplus12_exact_cross_retailer",
        "smartphone",
        "OnePlus 12 16GB 512GB Silky Black",
        {"brand": "oneplus", "family": "oneplus_12", "ram_gb": 16, "storage_gb": 512, "model_codes": ["CPH2573"]},
        "OnePlus 12 (16 GB RAM, 512 GB Storage) CPH2573",
        {"brand": "oneplus", "family": "oneplus_12", "ram_gb": 16, "storage_gb": 512, "model_codes": ["CPH2573"]},
        "exact",
    ),
    _p(
        "phone_oneplus12_storage_variant",
        "smartphone",
        "OnePlus 12 12GB 256GB",
        {"brand": "oneplus", "family": "oneplus_12", "ram_gb": 12, "storage_gb": 256, "model_codes": ["CPH2573"]},
        "OnePlus 12 16GB 512GB",
        {"brand": "oneplus", "family": "oneplus_12", "ram_gb": 16, "storage_gb": 512, "model_codes": ["CPH2573"]},
        "variant",
    ),
    _p(
        "phone_samsung_vs_apple_conflict",
        "smartphone",
        "Samsung Galaxy S24 256GB",
        {"brand": "samsung", "family": "galaxy_s24", "storage_gb": 256},
        "Apple iPhone 15 256GB",
        {"brand": "apple", "family": "iphone_15", "storage_gb": 256},
        "conflict",
    ),
    _p(
        "phone_nothing_2_vs_2a",
        "smartphone",
        "Nothing Phone 2 12GB 256GB",
        {"brand": "nothing", "family": "phone_2", "ram_gb": 12, "storage_gb": 256, "model_codes": ["A065"]},
        "Nothing Phone 2a 8GB 128GB",
        {"brand": "nothing", "family": "phone_2a", "ram_gb": 8, "storage_gb": 128, "model_codes": ["A059"]},
        "related",
    ),
    _p(
        "phone_moto_edge50_storage",
        "smartphone",
        "Motorola Edge 50 8GB 128GB",
        {"brand": "motorola", "family": "edge_50", "ram_gb": 8, "storage_gb": 128, "model_codes": ["XT2407-1"]},
        "Motorola Edge 50 8GB 256GB",
        {"brand": "motorola", "family": "edge_50", "ram_gb": 8, "storage_gb": 256, "model_codes": ["XT2407-1"]},
        "variant",
    ),
    _p(
        "phone_vivo_v30_vs_v30_pro",
        "smartphone",
        "Vivo V30 8GB 256GB",
        {"brand": "vivo", "family": "v30", "ram_gb": 8, "storage_gb": 256, "model_codes": ["V2318"]},
        "Vivo V30 Pro 8GB 256GB",
        {"brand": "vivo", "family": "v30_pro", "ram_gb": 8, "storage_gb": 256, "model_codes": ["V2319"]},
        "related",
    ),
    _p(
        "phone_realme_12_vs_12_pro",
        "smartphone",
        "realme 12 8GB 128GB",
        {"brand": "realme", "family": "realme_12", "ram_gb": 8, "storage_gb": 128, "model_codes": ["RMX3999"]},
        "realme 12 Pro 8GB 256GB",
        {"brand": "realme", "family": "realme_12_pro", "ram_gb": 8, "storage_gb": 256, "model_codes": ["RMX3840"]},
        "related",
    ),
    _p(
        "phone_nord_vs_nord_ce",
        "smartphone",
        "OnePlus Nord 4 8GB 256GB",
        {"brand": "oneplus", "family": "nord_4", "ram_gb": 8, "storage_gb": 256, "model_codes": ["CPH2661"]},
        "OnePlus Nord CE 4 8GB 256GB",
        {"brand": "oneplus", "family": "nord_ce4", "ram_gb": 8, "storage_gb": 256, "model_codes": ["CPH2613"]},
        "related",
    ),
    _p(
        "phone_google_vs_nothing_conflict",
        "smartphone",
        "Google Pixel 8 128GB",
        {"brand": "google", "family": "pixel_8", "storage_gb": 128},
        "Nothing Phone 2 128GB",
        {"brand": "nothing", "family": "phone_2", "storage_gb": 128},
        "conflict",
    ),
    # --- Laptops: GPU / CPU / RAM / storage / chassis ---
    _p(
        "laptop_loq_exact_cross_title",
        "laptop",
        "Lenovo LOQ 15IAX9 Intel Core i5 16GB 512GB RTX 4050",
        {
            "brand": "lenovo",
            "family": "loq_15",
            "model_codes": ["83GS003HIN"],
            "ram_gb": 16,
            "storage_gb": 512,
            "cpu_models": ["i5-12450HX"],
            "gpu": "rtx 4050",
        },
        "Lenovo LOQ 15IAX9 (16 GB / 512 GB / RTX 4050) 83GS003HIN",
        {
            "brand": "lenovo",
            "family": "loq_15",
            "model_codes": ["83GS003HIN"],
            "ram_gb": 16,
            "storage_gb": 512,
            "cpu_models": ["i5-12450HX"],
            "gpu": "rtx 4050",
        },
        "exact",
    ),
    _p(
        "laptop_same_chassis_ram_8_vs_16",
        "laptop",
        "ASUS Vivobook 15 X1504VA 8GB 512GB",
        {"brand": "asus", "family": "vivobook_15", "model_codes": ["X1504VA"], "ram_gb": 8, "storage_gb": 512},
        "ASUS Vivobook 15 X1504VA 16GB 512GB",
        {"brand": "asus", "family": "vivobook_15", "model_codes": ["X1504VA"], "ram_gb": 16, "storage_gb": 512},
        "variant",
    ),
    _p(
        "laptop_same_chassis_512_vs_1tb",
        "laptop",
        "HP Pavilion 15 16GB 512GB",
        {"brand": "hp", "family": "pavilion_15", "model_codes": ["eg3036TU"], "ram_gb": 16, "storage_gb": 512},
        "HP Pavilion 15 16GB 1TB",
        {"brand": "hp", "family": "pavilion_15", "model_codes": ["eg3036TU"], "ram_gb": 16, "storage_gb": 1024},
        "variant",
    ),
    _p(
        "laptop_rtx4050_vs_4060",
        "laptop",
        "Lenovo LOQ 15 RTX 4050 16GB 512GB",
        {"brand": "lenovo", "family": "loq_15", "model_codes": ["83GS003HIN"], "ram_gb": 16, "storage_gb": 512, "gpu": "rtx 4050"},
        "Lenovo LOQ 15 RTX 4060 16GB 512GB",
        {"brand": "lenovo", "family": "loq_15", "model_codes": ["83GS008WIN"], "ram_gb": 16, "storage_gb": 512, "gpu": "rtx 4060"},
        "variant",
    ),
    _p(
        "laptop_i5_1335u_vs_i7_1355u",
        "laptop",
        "Dell Inspiron 14 i5-1335U 16GB 512GB",
        {
            "brand": "dell",
            "family": "inspiron_14",
            "model_codes": ["5440"],
            "ram_gb": 16,
            "storage_gb": 512,
            "cpu_models": ["i5-1335U"],
        },
        "Dell Inspiron 14 i7-1355U 16GB 512GB",
        {
            "brand": "dell",
            "family": "inspiron_14",
            "model_codes": ["5440"],
            "ram_gb": 16,
            "storage_gb": 512,
            "cpu_models": ["i7-1355U"],
        },
        "variant",
    ),
    _p(
        "laptop_14_vs_15_inch",
        "laptop",
        "HP Pavilion 14 16GB 512GB",
        {"brand": "hp", "family": "pavilion", "model_codes": ["dv2015TU"], "ram_gb": 16, "storage_gb": 512, "screen_inch": 14},
        "HP Pavilion 15 16GB 512GB",
        {"brand": "hp", "family": "pavilion", "model_codes": ["eg3036TU"], "ram_gb": 16, "storage_gb": 512, "screen_inch": 15.6},
        "variant",
    ),
    _p(
        "laptop_thinkpad_t14_gen4_vs_gen5",
        "laptop",
        "Lenovo ThinkPad T14 Gen 4 i7 16GB 512GB",
        {"brand": "lenovo", "family": "thinkpad_t14", "model_codes": ["21HD004MIG"], "ram_gb": 16, "storage_gb": 512, "generation": "gen4"},
        "Lenovo ThinkPad T14 Gen 5 Ultra 7 16GB 512GB",
        {"brand": "lenovo", "family": "thinkpad_t14", "model_codes": ["21ML004NIG"], "ram_gb": 16, "storage_gb": 512, "generation": "gen5"},
        "variant",
    ),
    _p(
        "laptop_macbook_air_m2_vs_m3",
        "laptop",
        "Apple MacBook Air 13 M2 8GB 256GB",
        {"brand": "apple", "family": "macbook_air_13", "model_codes": ["MLXY3HN/A"], "ram_gb": 8, "storage_gb": 256, "cpu_models": ["m2"]},
        "Apple MacBook Air 13 M3 8GB 256GB",
        {"brand": "apple", "family": "macbook_air_13", "model_codes": ["MRXN3HN/A"], "ram_gb": 8, "storage_gb": 256, "cpu_models": ["m3"]},
        "variant",
    ),
    _p(
        "laptop_macbook_air_vs_pro",
        "laptop",
        "Apple MacBook Air 13 M3 8GB 256GB",
        {"brand": "apple", "family": "macbook_air_13", "ram_gb": 8, "storage_gb": 256, "model_codes": ["MRXN3HN/A"]},
        "Apple MacBook Pro 14 M3 8GB 512GB",
        {"brand": "apple", "family": "macbook_pro_14", "ram_gb": 8, "storage_gb": 512, "model_codes": ["MTL73HN/A"]},
        "related",
    ),
    _p(
        "laptop_hp_vs_dell_conflict",
        "laptop",
        "HP Pavilion 15 16GB 512GB",
        {"brand": "hp", "family": "pavilion_15", "ram_gb": 16, "storage_gb": 512},
        "Dell Inspiron 15 16GB 512GB",
        {"brand": "dell", "family": "inspiron_15", "ram_gb": 16, "storage_gb": 512},
        "conflict",
    ),
    _p(
        "laptop_iris_xe_vs_rtx3050",
        "laptop",
        "ASUS Vivobook 15 Intel Iris Xe 16GB 512GB",
        {"brand": "asus", "family": "vivobook_15", "model_codes": ["X1504VA"], "ram_gb": 16, "storage_gb": 512, "gpu": "iris xe"},
        "ASUS TUF Gaming F15 RTX 3050 16GB 512GB",
        {"brand": "asus", "family": "tuf_f15", "model_codes": ["FX507ZC4"], "ram_gb": 16, "storage_gb": 512, "gpu": "rtx 3050"},
        "related",
    ),
    _p(
        "laptop_ryzen5_vs_ryzen7",
        "laptop",
        "Lenovo IdeaPad Slim 3 Ryzen 5 16GB 512GB",
        {"brand": "lenovo", "family": "ideapad_slim_3", "model_codes": ["83ER008HIN"], "ram_gb": 16, "storage_gb": 512, "cpu_models": ["ryzen 5 7520u"]},
        "Lenovo IdeaPad Slim 3 Ryzen 7 16GB 512GB",
        {"brand": "lenovo", "family": "ideapad_slim_3", "model_codes": ["83ER008JIN"], "ram_gb": 16, "storage_gb": 512, "cpu_models": ["ryzen 7 7730u"]},
        "variant",
    ),
    _p(
        "laptop_yoga_vs_ideapad",
        "laptop",
        "Lenovo Yoga Slim 7 16GB 512GB",
        {"brand": "lenovo", "family": "yoga_slim_7", "ram_gb": 16, "storage_gb": 512, "model_codes": ["83CV003NIN"]},
        "Lenovo IdeaPad Slim 5 16GB 512GB",
        {"brand": "lenovo", "family": "ideapad_slim_5", "ram_gb": 16, "storage_gb": 512, "model_codes": ["83DC003WIN"]},
        "related",
    ),
    _p(
        "laptop_near_identical_model_codes",
        "laptop",
        "ASUS Vivobook 16 X1605VA 16GB 512GB",
        {"brand": "asus", "family": "vivobook_16", "model_codes": ["X1605VA"], "ram_gb": 16, "storage_gb": 512},
        "ASUS Vivobook 16 X1605ZA 16GB 512GB",
        {"brand": "asus", "family": "vivobook_16", "model_codes": ["X1605ZA"], "ram_gb": 16, "storage_gb": 512},
        "variant",
    ),
    _p(
        "laptop_surface_vs_thinkpad_conflict",
        "laptop",
        "Microsoft Surface Laptop 6 16GB 512GB",
        {"brand": "microsoft", "family": "surface_laptop", "ram_gb": 16, "storage_gb": 512},
        "Lenovo ThinkPad T14 16GB 512GB",
        {"brand": "lenovo", "family": "thinkpad_t14", "ram_gb": 16, "storage_gb": 512},
        "conflict",
    ),
    # --- Televisions ---
    _p(
        "tv_same_series_43_vs_55",
        "television",
        "Samsung Crystal 4K 43 inch UA43CUE60AKLXL",
        {"brand": "samsung", "family": "crystal_4k", "screen_size_inch": 43, "model_codes": ["UA43CUE60AKLXL"]},
        "Samsung Crystal 4K 55 inch UA55CUE60AKLXL",
        {"brand": "samsung", "family": "crystal_4k", "screen_size_inch": 55, "model_codes": ["UA55CUE60AKLXL"]},
        "variant",
    ),
    _p(
        "tv_same_series_50_vs_55",
        "television",
        "LG UR75 50 inch 4K Smart TV",
        {"brand": "lg", "family": "ur75", "screen_size_inch": 50, "model_codes": ["50UR7500PSC"]},
        "LG UR75 55 inch 4K Smart TV",
        {"brand": "lg", "family": "ur75", "screen_size_inch": 55, "model_codes": ["55UR7500PSC"]},
        "variant",
    ),
    _p(
        "tv_same_series_55_vs_65",
        "television",
        "Sony Bravia 2 55 inch 4K Google TV",
        {"brand": "sony", "family": "bravia_2", "screen_size_inch": 55, "model_codes": ["K-55S25"]},
        "Sony Bravia 2 65 inch 4K Google TV",
        {"brand": "sony", "family": "bravia_2", "screen_size_inch": 65, "model_codes": ["K-65S25"]},
        "variant",
    ),
    _p(
        "tv_generation_year_mismatch",
        "television",
        "Samsung Crystal 4K 55 inch 2023",
        {"brand": "samsung", "family": "crystal_4k", "screen_size_inch": 55, "model_codes": ["UA55CUE60AKLXL"], "generation": "2023"},
        "Samsung Crystal 4K 55 inch 2024",
        {"brand": "samsung", "family": "crystal_4k", "screen_size_inch": 55, "model_codes": ["UA55DUE60AKLXL"], "generation": "2024"},
        "variant",
    ),
    _p(
        "tv_bravia_7_vs_8",
        "television",
        "Sony Bravia 7 65 inch Mini LED",
        {"brand": "sony", "family": "bravia_7", "screen_size_inch": 65, "model_codes": ["K-65XR70"]},
        "Sony Bravia 8 65 inch OLED",
        {"brand": "sony", "family": "bravia_8", "screen_size_inch": 65, "model_codes": ["K-65XR80"]},
        "related",
    ),
    _p(
        "tv_samsung_vs_lg_conflict",
        "television",
        "Samsung 55 inch 4K Smart TV",
        {"brand": "samsung", "family": "crystal_4k", "screen_size_inch": 55},
        "LG 55 inch 4K Smart TV",
        {"brand": "lg", "family": "ur75", "screen_size_inch": 55},
        "conflict",
    ),
    _p(
        "tv_qled_vs_oled_related",
        "television",
        "Samsung QLED 55 inch Q60C",
        {"brand": "samsung", "family": "q60c", "screen_size_inch": 55, "model_codes": ["QA55Q60CAKLXL"]},
        "Samsung OLED 55 inch S90C",
        {"brand": "samsung", "family": "s90c", "screen_size_inch": 55, "model_codes": ["QA55S90CAKLXL"]},
        "related",
    ),
    _p(
        "tv_exact_marketing_noise",
        "television",
        "Sony Bravia 2 55 inch 4K Google TV No Cost EMI",
        {"brand": "sony", "family": "bravia_2", "screen_size_inch": 55, "model_codes": ["K-55S25"]},
        "Sony BRAVIA 2 55\" 4K Google TV K-55S25",
        {"brand": "sony", "family": "bravia_2", "screen_size_inch": 55, "model_codes": ["K-55S25"]},
        "exact",
    ),
    _p(
        "tv_similar_titles_missing_size_related",
        "television",
        "Samsung Crystal 4K Smart TV",
        {"brand": "samsung", "family": "crystal_4k", "model_codes": []},
        "Samsung Crystal 4K 55 inch Smart TV",
        {"brand": "samsung", "family": "crystal_4k", "screen_size_inch": 55, "model_codes": []},
        "related",
    ),
    _p(
        "tv_43_vs_50_same_family",
        "television",
        "Xiaomi A Pro 43 inch 4K",
        {"brand": "xiaomi", "family": "a_pro", "screen_size_inch": 43, "model_codes": ["L43M8-A2IN"]},
        "Xiaomi A Pro 50 inch 4K",
        {"brand": "xiaomi", "family": "a_pro", "screen_size_inch": 50, "model_codes": ["L50M8-A2IN"]},
        "variant",
    ),
    # --- Refrigerators ---
    _p(
        "fridge_253_vs_260_close_capacity",
        "refrigerator",
        "Samsung 253L Double Door Refrigerator",
        {"brand": "samsung", "family": "samsung_double_door", "capacity_l": 253, "door_type": "double_door", "model_codes": ["RT28C3733S8"]},
        "Samsung 260L Double Door Refrigerator",
        {"brand": "samsung", "family": "samsung_double_door", "capacity_l": 260, "door_type": "double_door", "model_codes": ["RT28C3922S8"]},
        "variant",
    ),
    _p(
        "fridge_double_vs_single_door",
        "refrigerator",
        "LG 190L Single Door Refrigerator",
        {"brand": "lg", "family": "lg_single_door", "capacity_l": 190, "door_type": "single_door", "model_codes": ["GL-B199OSEB"]},
        "LG 190L Double Door Refrigerator",
        {"brand": "lg", "family": "lg_double_door", "capacity_l": 190, "door_type": "double_door", "model_codes": ["GL-S199OSEB"]},
        "variant",
    ),
    _p(
        "fridge_double_vs_side_by_side",
        "refrigerator",
        "Samsung 324L Double Door",
        {"brand": "samsung", "family": "samsung_double_door", "capacity_l": 324, "door_type": "double_door", "model_codes": ["RT34C4523S8"]},
        "Samsung 653L Side by Side",
        {"brand": "samsung", "family": "samsung_sbs", "capacity_l": 653, "door_type": "side_by_side", "model_codes": ["RS76CG8003S9"]},
        "related",
    ),
    _p(
        "fridge_samsung_vs_lg_conflict",
        "refrigerator",
        "Samsung 253L Double Door",
        {"brand": "samsung", "family": "samsung_double_door", "capacity_l": 253, "door_type": "double_door"},
        "LG 260L Double Door",
        {"brand": "lg", "family": "lg_double_door", "capacity_l": 260, "door_type": "double_door"},
        "conflict",
    ),
    _p(
        "fridge_exact_model_cross_title",
        "refrigerator",
        "Whirlpool 265 L Frost Free Double Door",
        {"brand": "whirlpool", "family": "whirlpool_ff", "capacity_l": 265, "door_type": "double_door", "model_codes": ["IFINV CNV 278"]},
        "Whirlpool 265L Frost-Free Double Door IFINV CNV 278",
        {"brand": "whirlpool", "family": "whirlpool_ff", "capacity_l": 265, "door_type": "double_door", "model_codes": ["IFINV CNV 278"]},
        "exact",
    ),
    _p(
        "fridge_variant_suffix",
        "refrigerator",
        "Godrej 236L Double Door RD EDGEPRO 236C 33 TDI",
        {"brand": "godrej", "family": "edgepro", "capacity_l": 236, "door_type": "double_door", "model_codes": ["RD EDGEPRO 236C 33 TDI"]},
        "Godrej 236L Double Door RD EDGEPRO 236C 33 TDI PEARL",
        {"brand": "godrej", "family": "edgepro", "capacity_l": 236, "door_type": "double_door", "model_codes": ["RD EDGEPRO 236C 33 TDI PEARL"]},
        "variant",
    ),
    _p(
        "fridge_189_vs_192_within_family",
        "refrigerator",
        "Haier 189L Single Door",
        {"brand": "haier", "family": "haier_single", "capacity_l": 189, "door_type": "single_door", "model_codes": ["HED-19TMF"]},
        "Haier 195L Single Door",
        {"brand": "haier", "family": "haier_single", "capacity_l": 195, "door_type": "single_door", "model_codes": ["HED-20TMF"]},
        "variant",
    ),
    _p(
        "fridge_missing_capacity_related",
        "refrigerator",
        "Samsung Double Door Refrigerator",
        {"brand": "samsung", "family": "samsung_double_door", "door_type": "double_door", "model_codes": []},
        "Samsung 253L Double Door Refrigerator",
        {"brand": "samsung", "family": "samsung_double_door", "capacity_l": 253, "door_type": "double_door", "model_codes": []},
        "related",
    ),
    # --- Washing machines ---
    _p(
        "washer_7_vs_7_5_kg",
        "washing_machine",
        "LG 7kg Fully Automatic Front Load",
        {"brand": "lg", "capacity_kg": 7.0, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["FHV1207Z2M"]},
        "LG 7.5kg Fully Automatic Front Load",
        {"brand": "lg", "capacity_kg": 7.5, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["FHV1207Z4M"]},
        "variant",
    ),
    _p(
        "washer_7_vs_8_kg",
        "washing_machine",
        "Samsung 7kg Fully Automatic Front Load",
        {"brand": "samsung", "capacity_kg": 7.0, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["WW70T4020EE"]},
        "Samsung 8kg Fully Automatic Front Load",
        {"brand": "samsung", "capacity_kg": 8.0, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["WW80T4040EE"]},
        "variant",
    ),
    _p(
        "washer_front_vs_top",
        "washing_machine",
        "IFB 7kg Fully Automatic Front Load",
        {"brand": "ifb", "capacity_kg": 7.0, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["NEO DIVA SX"]},
        "IFB 7kg Fully Automatic Top Load",
        {"brand": "ifb", "capacity_kg": 7.0, "load_type": "top_load", "automation_type": "fully_automatic", "model_codes": ["TL-RDG 7.0KG"]},
        "variant",
    ),
    _p(
        "washer_semi_vs_fully",
        "washing_machine",
        "Whirlpool 7kg Semi Automatic Top Load",
        {"brand": "whirlpool", "capacity_kg": 7.0, "load_type": "top_load", "automation_type": "semi_automatic", "model_codes": ["Superb Atom 70S"]},
        "Whirlpool 7kg Fully Automatic Top Load",
        {"brand": "whirlpool", "capacity_kg": 7.0, "load_type": "top_load", "automation_type": "fully_automatic", "model_codes": ["Whitemagic Classic 7010"]},
        "variant",
    ),
    _p(
        "washer_lg_vs_samsung_conflict",
        "washing_machine",
        "LG 8kg Front Load",
        {"brand": "lg", "capacity_kg": 8.0, "load_type": "front_load"},
        "Samsung 8kg Front Load",
        {"brand": "samsung", "capacity_kg": 8.0, "load_type": "front_load"},
        "conflict",
    ),
    _p(
        "washer_exact_model_cross_title",
        "washing_machine",
        "Bosch 8 kg Front Load Serie 4",
        {"brand": "bosch", "capacity_kg": 8.0, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["WAJ2846WIN"]},
        "Bosch Serie 4 8kg Fully Automatic Front Load WAJ2846WIN",
        {"brand": "bosch", "capacity_kg": 8.0, "load_type": "front_load", "automation_type": "fully_automatic", "model_codes": ["WAJ2846WIN"]},
        "exact",
    ),
    _p(
        "washer_6_5_vs_7",
        "washing_machine",
        "Panasonic 6.5kg Fully Automatic Top Load",
        {"brand": "panasonic", "capacity_kg": 6.5, "load_type": "top_load", "automation_type": "fully_automatic", "model_codes": ["NA-F65H7RRB"]},
        "Panasonic 7kg Fully Automatic Top Load",
        {"brand": "panasonic", "capacity_kg": 7.0, "load_type": "top_load", "automation_type": "fully_automatic", "model_codes": ["NA-F70H7RRB"]},
        "variant",
    ),
    _p(
        "washer_near_model_code",
        "washing_machine",
        "LG 8kg Front Load FHV1408Z2M",
        {"brand": "lg", "capacity_kg": 8.0, "load_type": "front_load", "model_codes": ["FHV1408Z2M"]},
        "LG 8kg Front Load FHV1408Z4M",
        {"brand": "lg", "capacity_kg": 8.0, "load_type": "front_load", "model_codes": ["FHV1408Z4M"]},
        "variant",
    ),
    # --- Cameras ---
    _p(
        "camera_body_vs_18_55_kit",
        "camera",
        "Canon EOS R50 Mirrorless Camera Body Only",
        {"brand": "canon", "family": "eos_r50", "model_codes": ["R50"], "body_only": True},
        "Canon EOS R50 Mirrorless Camera 18-45mm Kit",
        {"brand": "canon", "family": "eos_r50", "model_codes": ["R50"], "body_only": False, "kit_lens": "18-45mm"},
        "variant",
    ),
    _p(
        "camera_18_45_vs_18_55_kit",
        "camera",
        "Canon EOS R10 18-45mm Kit",
        {"brand": "canon", "family": "eos_r10", "model_codes": ["R10"], "kit_lens": "18-45mm"},
        "Canon EOS R10 18-150mm Kit",
        {"brand": "canon", "family": "eos_r10", "model_codes": ["R10"], "kit_lens": "18-150mm"},
        "variant",
    ),
    _p(
        "camera_18_55_vs_dual_kit",
        "camera",
        "Nikon Z50 16-50mm Kit",
        {"brand": "nikon", "family": "z50", "model_codes": ["Z50"], "kit_lens": "16-50mm"},
        "Nikon Z50 Double Zoom Kit 16-50mm + 50-250mm",
        {"brand": "nikon", "family": "z50", "model_codes": ["Z50"], "kit_lens": "16-50mm+50-250mm"},
        "variant",
    ),
    _p(
        "camera_a7m4_vs_a7m3",
        "camera",
        "Sony Alpha ILCE-7M4 Body",
        {"brand": "sony", "family": "alpha_7", "model_codes": ["ILCE-7M4"], "body_only": True, "generation": "m4"},
        "Sony Alpha ILCE-7M3 Body",
        {"brand": "sony", "family": "alpha_7", "model_codes": ["ILCE-7M3"], "body_only": True, "generation": "m3"},
        "variant",
    ),
    _p(
        "camera_canon_vs_sony_conflict",
        "camera",
        "Canon EOS R8 Body",
        {"brand": "canon", "family": "eos_r8", "body_only": True},
        "Sony Alpha ILCE-7C Body",
        {"brand": "sony", "family": "alpha_7c", "body_only": True},
        "conflict",
    ),
    _p(
        "camera_exact_body_cross_title",
        "camera",
        "Sony Alpha ILCE-6700 Mirrorless Camera Body Only",
        {"brand": "sony", "family": "alpha_6700", "model_codes": ["ILCE-6700"], "body_only": True},
        "Sony A6700 Body (ILCE-6700)",
        {"brand": "sony", "family": "alpha_6700", "model_codes": ["ILCE-6700"], "body_only": True},
        "exact",
    ),
    _p(
        "camera_a6700_vs_a7c",
        "camera",
        "Sony Alpha ILCE-6700 Body",
        {"brand": "sony", "family": "alpha_6700", "model_codes": ["ILCE-6700"], "body_only": True},
        "Sony Alpha ILCE-7C Body",
        {"brand": "sony", "family": "alpha_7c", "model_codes": ["ILCE-7C"], "body_only": True},
        "related",
    ),
    _p(
        "camera_r50_vs_r10",
        "camera",
        "Canon EOS R50 Body",
        {"brand": "canon", "family": "eos_r50", "model_codes": ["R50"], "body_only": True},
        "Canon EOS R10 Body",
        {"brand": "canon", "family": "eos_r10", "model_codes": ["R10"], "body_only": True},
        "related",
    ),
    _p(
        "camera_z50_body_vs_kit",
        "camera",
        "Nikon Z50 Body Only",
        {"brand": "nikon", "family": "z50", "model_codes": ["Z50"], "body_only": True},
        "Nikon Z50 16-50mm Kit",
        {"brand": "nikon", "family": "z50", "model_codes": ["Z50"], "kit_lens": "16-50mm"},
        "variant",
    ),
    # --- Headphones ---
    _p(
        "headphones_xm4_vs_xm5",
        "headphones",
        "Sony WH-1000XM4 Wireless Headphones",
        {"brand": "sony", "family": "wh1000x", "model_codes": ["WH-1000XM4"], "generation": "xm4", "connectivity": "wireless"},
        "Sony WH-1000XM5 Wireless Headphones",
        {"brand": "sony", "family": "wh1000x", "model_codes": ["WH-1000XM5"], "generation": "xm5", "connectivity": "wireless"},
        "variant",
    ),
    _p(
        "headphones_wired_vs_wireless",
        "headphones",
        "Sony MDR-ZX310AP Wired Headphones",
        {"brand": "sony", "family": "mdr_zx", "model_codes": ["MDR-ZX310AP"], "connectivity": "wired", "form_factor": "on_ear"},
        "Sony WH-CH520 Wireless Headphones",
        {"brand": "sony", "family": "wh_ch", "model_codes": ["WH-CH520"], "connectivity": "wireless", "form_factor": "on_ear"},
        "related",
    ),
    _p(
        "headphones_overear_vs_inear",
        "headphones",
        "Sony WH-1000XM5 Over Ear",
        {"brand": "sony", "family": "wh1000x", "model_codes": ["WH-1000XM5"], "form_factor": "over_ear", "connectivity": "wireless"},
        "Sony WI-C100 In Ear Neckband",
        {"brand": "sony", "family": "wi_c", "model_codes": ["WI-C100"], "form_factor": "in_ear", "connectivity": "wireless"},
        "related",
    ),
    _p(
        "headphones_sony_vs_bose_conflict",
        "headphones",
        "Sony WH-1000XM5 Wireless Headphones",
        {"brand": "sony", "family": "wh1000x", "connectivity": "wireless"},
        "Bose QuietComfort 45 Wireless Headphones",
        {"brand": "bose", "family": "qc45", "connectivity": "wireless"},
        "conflict",
    ),
    _p(
        "headphones_exact_xm5_cross_title",
        "headphones",
        "Sony WH-1000XM5 Wireless Noise Cancelling Headphones Black",
        {"brand": "sony", "family": "wh1000x", "model_codes": ["WH-1000XM5"], "connectivity": "wireless"},
        "Sony WH1000XM5 Bluetooth Headphones WH-1000XM5",
        {"brand": "sony", "family": "wh1000x", "model_codes": ["WH-1000XM5"], "connectivity": "wireless"},
        "exact",
    ),
    _p(
        "headphones_qc45_vs_qc_ultra",
        "headphones",
        "Bose QuietComfort 45",
        {"brand": "bose", "family": "qc45", "model_codes": ["QC45"], "connectivity": "wireless"},
        "Bose QuietComfort Ultra Headphones",
        {"brand": "bose", "family": "qc_ultra", "model_codes": ["QCULTRA"], "connectivity": "wireless"},
        "related",
    ),
    _p(
        "headphones_anc_vs_non_anc_sku",
        "headphones",
        "JBL Tune 720BT Wireless",
        {"brand": "jbl", "family": "tune_720", "model_codes": ["720BT"], "connectivity": "wireless"},
        "JBL Tune 770NC Wireless ANC",
        {"brand": "jbl", "family": "tune_770", "model_codes": ["770NC"], "connectivity": "wireless"},
        "related",
    ),
    _p(
        "headphones_same_family_wired_wireless",
        "headphones",
        "Audio-Technica ATH-M50x Wired",
        {"brand": "audio-technica", "family": "ath_m50x", "model_codes": ["ATH-M50x"], "connectivity": "wired", "form_factor": "over_ear"},
        "Audio-Technica ATH-M50xBT2 Wireless",
        {"brand": "audio-technica", "family": "ath_m50x", "model_codes": ["ATH-M50xBT2"], "connectivity": "wireless", "form_factor": "over_ear"},
        "variant",
    ),
    # --- TWS ---
    _p(
        "tws_airpods_pro_gen1_vs_gen2",
        "tws",
        "Apple AirPods Pro 1st Generation",
        {"brand": "apple", "family": "airpods_pro", "model_codes": ["MLWK3"], "generation": "1"},
        "Apple AirPods Pro 2nd Generation",
        {"brand": "apple", "family": "airpods_pro", "model_codes": ["MTJV3"], "generation": "2"},
        "variant",
    ),
    _p(
        "tws_buds2_vs_buds2_pro",
        "tws",
        "Samsung Galaxy Buds2",
        {"brand": "samsung", "family": "galaxy_buds2", "model_codes": ["SM-R177"], "generation": "buds2"},
        "Samsung Galaxy Buds2 Pro",
        {"brand": "samsung", "family": "galaxy_buds2_pro", "model_codes": ["SM-R510"], "generation": "buds2_pro"},
        "related",
    ),
    _p(
        "tws_wf_xm4_vs_xm5",
        "tws",
        "Sony WF-1000XM4 Truly Wireless",
        {"brand": "sony", "family": "wf1000x", "model_codes": ["WF-1000XM4"], "generation": "xm4"},
        "Sony WF-1000XM5 Truly Wireless",
        {"brand": "sony", "family": "wf1000x", "model_codes": ["WF-1000XM5"], "generation": "xm5"},
        "variant",
    ),
    _p(
        "tws_apple_vs_samsung_conflict",
        "tws",
        "Apple AirPods Pro 2",
        {"brand": "apple", "family": "airpods_pro", "generation": "2"},
        "Samsung Galaxy Buds2 Pro",
        {"brand": "samsung", "family": "galaxy_buds2_pro", "generation": "buds2_pro"},
        "conflict",
    ),
    _p(
        "tws_exact_buds_fe",
        "tws",
        "Samsung Galaxy Buds FE Graphite",
        {"brand": "samsung", "family": "galaxy_buds_fe", "model_codes": ["SM-R400"], "generation": "fe"},
        "Samsung Galaxy Buds FE (SM-R400) Graphite",
        {"brand": "samsung", "family": "galaxy_buds_fe", "model_codes": ["SM-R400"], "generation": "fe"},
        "exact",
    ),
    _p(
        "tws_airpods_3_vs_pro",
        "tws",
        "Apple AirPods 3rd Generation",
        {"brand": "apple", "family": "airpods", "model_codes": ["MPNY3"], "generation": "3"},
        "Apple AirPods Pro 2nd Generation",
        {"brand": "apple", "family": "airpods_pro", "model_codes": ["MTJV3"], "generation": "2"},
        "related",
    ),
    _p(
        "tws_oneplus_buds3_vs_pro",
        "tws",
        "OnePlus Nord Buds 3",
        {"brand": "oneplus", "family": "nord_buds_3", "model_codes": ["E510A"], "generation": "3"},
        "OnePlus Nord Buds 3 Pro",
        {"brand": "oneplus", "family": "nord_buds_3_pro", "model_codes": ["E511A"], "generation": "3_pro"},
        "related",
    ),
    _p(
        "tws_boat_vs_noise_conflict",
        "tws",
        "boAt Airdopes 141",
        {"brand": "boat", "family": "airdopes_141"},
        "Noise Buds VS104",
        {"brand": "noise", "family": "vs104"},
        "conflict",
    ),
    _p(
        "tws_same_family_anc_sku",
        "tws",
        "Nothing Ear (a)",
        {"brand": "nothing", "family": "ear_a", "model_codes": ["EAR-A"], "generation": "a"},
        "Nothing Ear (a) ANC",
        {"brand": "nothing", "family": "ear_a", "model_codes": ["EAR-A-ANC"], "generation": "a"},
        "variant",
    ),
]
